services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro

  redis:
    image: redis:7.2-alpine
    container_name: ragchat-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  app:
    image: rag-chat-management  # Docker image name (built from Dockerfile)
    container_name: rag-chat-management  # Custom container name
    build: .  # Build from Dockerfile in current directory
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rag_db?serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_REDIS_HOST: redis  # Service name as hostname
      SPRING_REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

    # pgAdmin for database browsing
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ragchat-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ragchat.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"  # Access on http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped



volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  pgadmin-data:
    driver: local
